apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadvdmc9872-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadvdmc9872-tenant-component
    app.kubernetes.io/part-of: loadvdmc9872-tenant-app
  name: loadvdmc9872-tenant-component
  namespace: loadvdmc9872-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadvdmc9872-tenant-component
    weight: null
status: {}
